# Generated by Django 5.1.6 on 2025-02-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_influencer'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='followers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='influencer',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
