# Generated by Django 5.1.6 on 2025-02-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_influencer_description_influencer_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_choice',
            field=models.CharField(choices=[('advertise', 'Advertise'), ('influencer', 'Influencer')], default='influencer', max_length=200),
        ),
    ]
