# Generated by Django 5.1.6 on 2025-02-12 11:26

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_customuser_user_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('influencers', models.ManyToManyField(related_name='advertise', to='chat.influencer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advertise', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
